=== SzGabor1/V9ZK10_XML_Gyak/2023.10.04/V9ZK10_adatbazis.dtd
<!ELEMENT V9ZK10_adatbazis (dolgozo+)>
<!ELEMENT dolgozo (nev, fizetes)>
  <!ATTLIST dolgozo
    kod ID #REQUIRED>
<!ELEMENT nev (#PCDATA)>
<!ELEMENT fizetes (#PCDATA)>

=== SzGabor1/V9ZK10_XML_Gyak/2023.10.04/V9ZK10_adatbazis.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE V9ZK10_adatbazis SYSTEM "V9ZK10_adatbazis.dtd">
 <V9ZK10_adatbazis>
  <dolgozo kod="d001">
    <nev>Axel Rose</nev>
    <fizetes>130000</fizetes>
  </dolgozo>
  <dolgozo kod="d002">
    <nev>George Humphrey</nev>
    <fizetes>334000</fizetes>
  </dolgozo>
  <dolgozo kod="d003">
    <nev>Aaron Steel</nev>
    <fizetes>225000</fizetes>
  </dolgozo>
  <dolgozo kod="d004">
    <nev>John Doe</nev>
    <fizetes>735000</fizetes>
  </dolgozo>
 </V9ZK10_adatbazis>
